services:
  forwarder:
    image: fluent/fluent-bit:3.2.1
    volumes:
      - ./forwarder.conf:/fluent-bit/etc/fluent-bit.conf
  aggregator:
    image: fluent/fluent-bit:3.2.1
    ports:
      - "8888:8888"
    volumes:
      - ./aggregator.conf:/fluent-bit/etc/fluent-bit.conf
