networks:
  default:
    name: debug
    driver: bridge

services:
  tempo:
    image: &tempo_img grafana/tempo:2.6.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4319:4318"
    depends_on:
      - fluentbit

  tempo-mtls:
    image: *tempo_img
    container_name: tempo-mtls
    command: ["-config.file=/etc/tempo-mtls.yaml"]
    volumes:
      - ./tempo-mtls.yaml:/etc/tempo-mtls.yaml
      - ./certs/generated/tempo:/certs
    ports:
      - "3201:3200"
      - "4320:4318"
    depends_on:
      - fluentbit

  fluentbit:
    image: fluent/fluent-bit:3.2
    container_name: fluentbit
    ports:
      - 4318:4318
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./certs/generated/fb:/certs
